# Generated by Django 2.2.7 on 2019-12-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('primary', models.CharField(max_length=100)),
                ('secondary', models.CharField(max_length=100)),
                ('alt1', models.CharField(max_length=100)),
                ('alt2', models.CharField(max_length=100)),
                ('alt3', models.CharField(max_length=100)),
            ],
        ),
    ]
